### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by balbuze** [jue89/node-journalctl#2]
Hello!
I'm trying to use your job on my system.
In a console, I get what I need when using : `sudo journalctl -f -u brutefir`
it returns something like
`- Logs begin at Fri 2020-02-07 08:11:14 UTC. --
Feb 07 20:26:03 volumio-rpi4 volumio[14957]: Timers for benchmarking may be unreliable.
Feb 07 20:26:03 volumio-rpi4 volumio[14957]: Realtime priority 1 set for cli process (pid 14973)
Feb 07 20:26:03 volumio-rpi4 volumio[14957]: Realtime priority 3 set for input process (pid 14958)
Feb 07 20:26:03 volumio-rpi4 volumio[14957]: Realtime priority 4 set for filter process (pid 14972)
Feb 07 20:26:03 volumio-rpi4 volumio[14957]: Realtime priority 4 set for filter process (pid 14971)
Feb 07 20:26:03 volumio-rpi4 volumio[14957]: Realtime priority 3 set for output process (pid 14974)
Feb 07 20:26:03 volumio-rpi4 volumio[14957]: Fixed I/O-delay is 4096 samples
Feb 07 20:26:03 volumio-rpi4 volumio[14957]: Audio processing starts now
Feb 07 20:26:30 volumio-rpi4 systemd[1]: Stopping brutefir Daemon...
Feb 07 20:26:30 volumio-rpi4 systemd[1]: Stopped brutefir Daemon.
`
so ok. But I want to get this result using my javascript 
`ControllerBrutefir.prototype.getjournalctl = function() {
 var self = this;

let opts = {
unit: ['brutefir']
}

const journalctl = new Journalctl([opts]);

journalctl.on('event', (event) => {
console.log('log from brutefir : ' + event)
});

};`
but it returns nothing...
Could it be due to 'sudo' not use in your code?
Any idea?
Thank you

**Comment by jue89** [comment]
Hi!

Yes, that might be the problem. What happens if you omit `sudo`? Do you get any output?

**Comment by jue89** [comment]
I'm closing this. Feel free to open another one if you still need assistance or if you have a feature request (like being able to put `sudo` in front of the `journalctl` call).

**Comment by balbuze** [comment]
ok thanks
