### ISSUE TITLE
No events shown

### ISSUE THREAD

**Issue by yafp** [jue89/node-journalctl#3]
Hi,

i am trying to integrate journalctl 1.1.0 into a project of mine.

Based on the readme i did the following

```
const Journalctl = require('journalctl');
const journalctl = new Journalctl(['all']);

console.error(journalctl)

journalctl.on('event', (event) => {
  console.error(event)
});
```
I am running `watch journalctl -n 10` in a terminal to see what happens in journalctl, but none of those incoming events are shown in my javascript code using your node-journalctl.

Any idea what might cause my problem?

**Comment by jue89** [comment]
Hi!

Well, the docs may be a little bit misleading here. The symbols `[` and `]` around `opts` are an indicator, that `opts` can be omitted and is an optional parameter. Just change your code like this:

```js
const Journalctl = require('journalctl');
const journalctl = new Journalctl();

journalctl.on('event', (event) => {
  console.error(event)
});
```

Does this work for you?

**Comment by yafp** [comment]
> Does this work for you?

Yes it does. Thanks.
